package modelo;
// Generated 17 nov. 2022 18:59:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private BigDecimal precio;
     private Integer existencia;
     private Set<VentaDetalle> ventaDetalles = new HashSet<VentaDetalle>(0);

    public Producto() {
    }

	
    public Producto(int id) {
        this.id = id;
    }
    public Producto(int id, String descripcion, BigDecimal precio, Integer existencia, Set<VentaDetalle> ventaDetalles) {
       this.id = id;
       this.descripcion = descripcion;
       this.precio = precio;
       this.existencia = existencia;
       this.ventaDetalles = ventaDetalles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Integer getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(Integer existencia) {
        this.existencia = existencia;
    }
    public Set<VentaDetalle> getVentaDetalles() {
        return this.ventaDetalles;
    }
    
    public void setVentaDetalles(Set<VentaDetalle> ventaDetalles) {
        this.ventaDetalles = ventaDetalles;
    }




}


