package modelo;
// Generated 17 nov. 2022 18:59:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Date fecha;
     private BigDecimal total;
     private Set<VentaDetalle> ventaDetalles = new HashSet<VentaDetalle>(0);

    public Venta() {
    }

	
    public Venta(int id) {
        this.id = id;
    }
    public Venta(int id, Cliente cliente, Date fecha, BigDecimal total, Set<VentaDetalle> ventaDetalles) {
       this.id = id;
       this.cliente = cliente;
       this.fecha = fecha;
       this.total = total;
       this.ventaDetalles = ventaDetalles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Set<VentaDetalle> getVentaDetalles() {
        return this.ventaDetalles;
    }
    
    public void setVentaDetalles(Set<VentaDetalle> ventaDetalles) {
        this.ventaDetalles = ventaDetalles;
    }




}


