package modelo;
// Generated 17 nov. 2022 18:59:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VentaDetalle generated by hbm2java
 */
public class VentaDetalle  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private Venta venta;
     private Integer cantidad;
     private BigDecimal subtotal;

    public VentaDetalle() {
    }

	
    public VentaDetalle(int id, Producto producto, Venta venta) {
        this.id = id;
        this.producto = producto;
        this.venta = venta;
    }
    public VentaDetalle(int id, Producto producto, Venta venta, Integer cantidad, BigDecimal subtotal) {
       this.id = id;
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }




}


